apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: sangsangplus-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend
        image: buildingbite/sangsangplus-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: CACHE_BUST
          value: "v1.0.3"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sangsangplus-frontend
spec:
  type: ClusterIP
  selector:
    app: frontend-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80